template: |
  ## What's Changed

  $CHANGES
categories:
  - title: '🚀 New'
    label: 'enhancement'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    labels:
    - 'maintenance'
    - 'documentation'
    - 'dependencies'
