name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  # What's Changed

  $CHANGES
categories:
  - title: 'New'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Maintenance'
    label: 'maintenance'
  - title: 'Documentation'
    label: 'documentation'
  - title: 'Dependency Updates'
    label: 'dependencies'
