version: "3.7"

networks:
  coganet:

services:
  api-mocks:
    image: rodolpheche/wiremock
    volumes:
      - "./api-mocks:/home/wiremock"
    ports:
      - "8093:8080"
    networks:
      - coganet
    command: ["--verbose", "--no-request-journal"]

  backend:
    image: "cogboard/cogboard-app"
    volumes:
      - "./mnt:/data"
    networks:
      - coganet

  frontened:
    image: "cogboard/cogboard-web"
    depends_on:
      - "backend"
    networks:
      - coganet
    ports:
      - "80:80"
  cypress:
    image: "cypress/included:3.7.0"
    networks:
      - coganet
    depends_on:
      - "frontened"
    environment:
      - CYPRESS_baseUrl=http://frontened:80
    working_dir: /e2e
    volumes:
      - ./functional/cypress-tests:/e2e
    command: ["--browser", "chrome"]