export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const REQUEST_UPDATE = 'REQUEST_UPDATE';
export const UPDATE_WIDGET = 'UPDATE_WIDGET';
export const EDIT_WIDGET = 'EDIT_WIDGET';
export const ADD_WIDGET = 'ADD_WIDGET';
export const DELETE_WIDGET = 'DELETE_WIDGET';