name: Update Release Draft

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update Release Draft
        id: release_draft
        uses: release-drafter/release-drafter@v5.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Release Asset
        run: |
          ./gradlew prepareCogboardCompose
          zip -r cogboard cogboard-compose.yml mnt
      - name: Prepare props
        id: props
        run: |
          export VERSION=$(sed -n '1s/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/p' gradle.properties)
          echo "::set-output name=current_version::$VERSION"
      - name: Upload Release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_draft.outputs.upload_url }}
          asset_path: ./cogboard.zip
          asset_name: cogboard-${{ steps.props.outputs.current_version }}.zip
          asset_content_type: application/zip
